"""Client-side tile generation using mcmap binary."""

from __future__ import annotations

import json
import logging
import subprocess
from pathlib import Path

logger = logging.getLogger(__name__)


class ClientTiler:
    """Runs mcmap locally to generate PNG tiles from .mca files."""

    def __init__(self, mcmap_bin: Path, palette_path: Path, biome_colors_path: Path, biome_tints_path: Path):
        self.mcmap_bin = mcmap_bin
        self.palette_path = palette_path
        self.biome_colors_path = biome_colors_path
        self.biome_tints_path = biome_tints_path

    @classmethod
    def from_work_dir(cls, work_dir: Path) -> ClientTiler | None:
        """Create from standard work directory paths. Returns None if mcmap not found."""
        mcmap_bin = work_dir / "bin" / "mcmap"
        if not mcmap_bin.exists():
            # Try target/release path
            mcmap_bin = work_dir / "tiler" / "target" / "release" / "mcmap"
        if not mcmap_bin.exists():
            return None

        data_dir = work_dir / "data"
        palette = data_dir / "block_colors.json"
        biome_colors = data_dir / "biome_colors.json"
        biome_tints = data_dir / "biome_tint_blocks.json"

        return cls(mcmap_bin, palette, biome_colors, biome_tints)

    def render_region(self, region_mca: Path, output_dir: Path) -> dict[str, Path]:
        """Render all chunks in a region .mca file to PNGs.

        Returns dict mapping "chunk_{cx}_{cz}" -> Path to PNG file.
        """
        output_dir.mkdir(parents=True, exist_ok=True)

        cmd = [str(self.mcmap_bin)]
        for flag, path in [
            ("--palette", self.palette_path),
            ("--biome-colors", self.biome_colors_path),
            ("--biome-tints", self.biome_tints_path),
        ]:
            if path.exists():
                cmd.extend([flag, str(path)])
        cmd.extend([str(region_mca), "--all", "--output-dir", str(output_dir)])

        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=180)
            if result.returncode != 0:
                logger.error("mcmap render failed exit=%d stderr=%s", result.returncode, result.stderr[:500])
                return {}
        except subprocess.TimeoutExpired:
            logger.error("mcmap render timeout for %s", region_mca)
            return {}
        except Exception as e:
            logger.error("mcmap render error: %s", e)
            return {}

        # Collect generated files
        tiles = {}
        for png_path in output_dir.glob("chunk_*.png"):
            stem = png_path.stem  # chunk_123_456
            tiles[stem] = png_path
        return tiles

    def render_single(self, region_mca: Path, chunk_x: int, chunk_z: int, output_dir: Path) -> Path | None:
        """Render a single chunk."""
        output_dir.mkdir(parents=True, exist_ok=True)

        cmd = [str(self.mcmap_bin)]
        for flag, path in [
            ("--palette", self.palette_path),
            ("--biome-colors", self.biome_colors_path),
            ("--biome-tints", self.biome_tints_path),
        ]:
            if path.exists():
                cmd.extend([flag, str(path)])
        cmd.extend([str(region_mca), str(chunk_x), str(chunk_z), "--output-dir", str(output_dir)])

        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
            if result.returncode != 0:
                return None
        except Exception:
            return None

        png_path = output_dir / f"chunk_{chunk_x}_{chunk_z}.png"
        return png_path if png_path.exists() else None

    @staticmethod
    def parse_terrain_json(json_path: Path) -> dict | None:
        """Read terrain JSON generated by mcmap."""
        if not json_path.exists():
            return None
        try:
            return json.loads(json_path.read_text())
        except Exception:
            return None
