<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ChunkDMesh.Client</RootNamespace>
    <AssemblyName>ChunkDMesh</AssemblyName>
    <ApplicationIcon>Resources\icon.ico</ApplicationIcon>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Eto.Forms" Version="2.8.*" />
    <PackageReference Include="Eto.Platform.Gtk" Version="2.8.*" Condition="$([MSBuild]::IsOSPlatform('Linux'))" />
    <PackageReference Include="Eto.Platform.Wpf" Version="2.8.*" Condition="$([MSBuild]::IsOSPlatform('Windows'))" />
    <PackageReference Include="Eto.Platform.Mac64" Version="2.8.*" Condition="$([MSBuild]::IsOSPlatform('OSX'))" />
    <PackageReference Include="ZstdSharp" Version="0.7.2" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\Fonts\MaterialDesignIcons-Regular.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Icons\*.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
